<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="css/style.css">
		<title>Combat boxe</title>
	</head>
<body>
	<main id="home">
		<picture>
			<source type="image/webp" srcset="img/back.webp">
			<img src="img/back.jpg" alt="aceuil" style="width: 100%;">
		</picture>
		<div class="inner-header">
			<h1>BOXING JZONN</h1>
			<p>Style make fights.</p>
			<ul>
			<!-- <li><a href="index.php">Acceuil</a></li> -->
			<li><a href="boxer.php">Boxer</a></li>
			<li><a href="school.php">Boxing school</a></li>
			<li><a href="review.php">Fights reviews</a></li>
			</ul>
		</div>
	</main>

	<footer>
		<h2><a href="https://thejzonn.github.io/PortfolioV3/#/">thejzonn.github.io</a></h2>
		<p>Copyright (c) 2017 Jzonn BOXING All Rights Reserved.</p>
	</footer>
	<script src="jquery-3.2.1.js"></script>
	<script src="main.js"></script>
</body>
</html>
