<main>
 <section id="fighter">
   <img src="<?= $fighter['photo']; ?>" alt="<?= $fighter['id']; ?>">
   <h2><?= $fighter['firstName'] .'&emsp;' .$fighter['lastName']; ?></h2>
   <p><strong>Records:</strong> <span class="records"><?= $fighter['records']; ?></span></p>
   <p><strong>Power-hand:</strong> <?= $fighter['hand']; ?></p>
   <p><strong>Fight-style:</strong> <?= $fighter['style']; ?> boxing</p>
   <p><strong>Description:</strong> <?= $fighter['description']; ?></p>
 </section>
</main>
