<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="css/style.css">
  <title>Combat boxe</title>
</head>
<body>
  <header>
    <nav>
      <ul>
        <li><a href="index.php">Home</a></li>
        <li><a href="boxer.php">Boxer</a></li>
        <li><a href="school.php">Boxing school</a></li>
        <li><a href="review.php">Fights reviews</a></li>
      </ul>
    </nav>
  </header>

  <?php include $template.'.phtml'; ?>

  <footer>
    <h2><a href="https://ricafortjason.github.io">ricafortjason.github.io</a></h2>
    <p>Copyright (c) 2017 Jzonn BOXING All Rights Reserved.</p>
  </footer>
  <script src="jquery-3.2.1.js"></script>
  <script src="main.js"></script>
</body>
</html>
