<div class="title">
  <h1>Fight Review</h1>
</div>
<main>

  <article class="fight">
    <img src="http://setwood.com/demo/wp-content/uploads/2016/07/placeholder-250.jpg" alt="pac vs horn">
    <div class="fight-info">
      <h2>Pacquiao vs Horn</h2>
      <p>(02 july 2017)<br>Upcoming ...</p>
    </div>
  </article>

  <article class="fight">

    <img src="http://setwood.com/demo/wp-content/uploads/2016/07/placeholder-250.jpg" alt="pac vs horn">
    <div class="fight-info">
      <h2>Mayweather vs McGregor</h2>
      <p>(26 aug 2017)<br>Upcoming ...</p>
    </div>
  </article>

  <article class="fight">
    <img src="http://setwood.com/demo/wp-content/uploads/2016/07/placeholder-250.jpg" alt="pac vs horn">
    <div class="fight-info">
      <h2>Golovkin vs Canelo</h2>
      <p>(16 sep 2017)<br>Upcoming ...</p>
    </div>
  </article>

</main>
