<div class="title">
  <h1>School</h1>
</div>
<main>
  <section>
    <h2>The JAB</h2>
    <img src="http://gclub-th.net/wp-content/uploads/2015/10/manny-sbobet.jpg" alt="jab">
    <div class="more">
      <article class="none">
        <p>
          <span>THE JAB. </span>
          The direct punch.
          The most basic punch, yet the one with most technique possible. You probably heard during a fight commentator using term like stiff jab.
          <br>The most populars ones are:<br>
          - Basic Jab <br>
          - The flicker Jab <br>
          - Stiff Jab <br>
          Its mostly use to mesure distance, or create distance with the opponent. But it can be use to blind or hide a punch. And of course to set up a one two.
        </p>
      </article>
      <button type="button"><i class="fa fa-angle-double-down" aria-hidden="true"></i></button>
    </div>
  </section>
  <section>
    <h2>The STRAIGHT RIGHT/LEFT HAND</h2>
    <img src="http://i.dailymail.co.uk/i/pix/2015/05/03/10/2842656C00000578-3065798-Another_straight_punch_from_Mayweather_catches_Pacquiao_flush_in-a-22_1430646540255.jpg" alt="straight">
    <div class="more">
      <article class="none">
        <p>
          <span>THE STRAIGHT RIGHT/LEFT HAND. </span>
          The direct punch. Usually the power punch hand, its throw with all the momentum possible(hip toss). The punch once thrown open defense ,that why it is sometimes follow up by a duck/dip to prevent counter.
          It punch that look for the KO, and the one that the opponent look out for.
        </p>
      </article>
      <button type="button"><i class="fa fa-angle-double-down" aria-hidden="true"></i></button>
    </div>
  </section>
  <section>
    <h2>The UPPERCUT</h2>
    <img src="http://www.mightyfighter.com/wp-content/uploads/2013/01/marquez-uppercut.jpg" alt="uppercut">
    <div class="more">
      <article class="none">
        <p>
          <span>THE UPPERCUT. </span>
          The direct punch.
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. At aliquid incidunt sit vel neque molestiae odit architecto dolores, illum sint maxime laboriosam ab minus, nemo facilis ipsa ipsum nihil nulla?
        </p>
      </article>
      <button type="button"><i class="fa fa-angle-double-down" aria-hidden="true"></i></button>
    </div>
  </section>
  <section>
    <h2>The HOOK</h2>
    <img src="https://www.fighttips.com/wp-content/uploads/2013/08/combo.jpg" alt="hook">
    <div class="more">
      <article class="none">
        <p>
          <span>THE HOOK. </span>
          The direct punch.
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. At aliquid incidunt sit vel neque molestiae odit architecto dolores, illum sint maxime laboriosam ab minus, nemo facilis ipsa ipsum nihil nulla?
        </p>
      </article>
      <button type="button"><i class="fa fa-angle-double-down" aria-hidden="true"></i></button>
    </div>
  </section>
</main>
